### PR TITLE
Add ability to specify PHANTOMJS2_VERSION via env variable

### PR DESCRIPTION
**Pull request by mpderbec**
The PHANTOMJS2_DOWNLOAD_URL wasn't quite useful because you couldn't override the value in helper.version. This PR adds PHANTOMJS2_VERSION, which gives you what you need.

### CODE REVIEW

**Comment by mpderbec** [comment]
For some reason, npmjs.com is not showing 0.0.7 published -- did you mean to publish it?

**Comment by mpderbec** [comment]
Not to nag, but it would be really great if 0.0.7 got published to npmjs.com so that we could change our package.json and speed up our npm install...

**Comment by gskachkov** [comment]
Something going wrong during publish 0.0.7. It was published and during npm installed used 0.0.7, but npmjs is show 0.0.6 version. I've republished with version 0.1.0. Please take a look if everything is ok.

**Comment by mpderbec** [comment]
Works perfectly! Thank you.

**Pull request merged**
